[config]
default_to_workspace = false

[env]
PYTHON = "python3.11"

[tasks.build-ffi-flow]
condition = { files_modified = { input = ["**/Cargo.toml", "**/src/**/*.rs"], output = ["./target/**/*prime*"] }, platforms = ["linux"]}
dependencies = [ "build", "copy-lib" ]

[tasks.build]
condition = { files_modified = { input = ["**/Cargo.toml", "**/src/**/*.rs"], output = ["./target/**/*prime*"] } }
private = true
command = "cargo"
args = ["build", "--release"]

[tasks.copy-lib]
condition = { files_modified = { input = ["./target/release/librust_prime_generation.so"], output = ["rust_prime_generation.so"] }, platforms = ["linux"] }
private = true
command = "cp"
args = [ "./target/release/librust_prime_generation.so", "./rust_prime_generation.so" ]

[tasks.clean-ffi-flow]
condition = { platforms = ["linux"] }
dependencies = [ "clean", "clean-lib" ]

[tasks.clean]
command = "cargo"
args = [ "clean" ]

[tasks.clean-lib]
condition = { platforms = ["linux"] }
command = "rm"
args = [ "./rust_prime_generation.so" ]

[tasks.run-python]
dependencies = [ "build", "copy-lib" ]
command = "${PYTHON}"
args = ["prime_number.py", "10", "0"]

[tasks.run-rust]
dependencies = ["build"]
command = "./target/release/prime_generation_rs"
args = ["10"]
